name: nextjs-cloud-run

on:
  push:
    branches:
      - main

env:
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  SERVERLESS_VPC_CONNECTOR: ${{ secrets.SERVERLESS_VPC_CONNECTOR }}
  DB_URL: ${{ secrets.DB_URL }}
  CLOUD_RUN_REGION: us-central1
  CLOUDSQL_INSTANCE_ID: ${{ secrets.CLOUDSQL_INSTANCE_ID }}
  REPO_NAME: grocery-list

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This step is where our service account will be authenticated
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

      - name: Enable the necessary APIs and enable docker auth
        run: |-
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud --quiet auth configure-docker

      - name: Build and tag image
        run: |-
          docker build . --build-arg DATABASE_URL=$DB_URL --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"

      - name: Push image to GCR
        run: |-
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Run db migrations
        run: |-
          gcloud components install beta --quiet
          gcloud beta run jobs create "db-migrations-${GITHUB_SHA::7}" --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
            --set-env-vars DATABASE_URL=$DB_URL \
            --set-cloudsql-instances $CLOUD_RUN_PROJECT_ID:$CLOUD_RUN_REGION:$CLOUDSQL_INSTANCE_ID \
            --vpc-connector $SERVERLESS_VPC_CONNECTOR \
            --region $CLOUD_RUN_REGION \
            --command "/bin/sh" --args="/app/scripts/migrate.sh" \
            --wait

      - name: Deploy
        run: |-
          gcloud components install beta --quiet
          gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
            --project $CLOUD_RUN_PROJECT_ID \
            --platform managed \
            --region $CLOUD_RUN_REGION \
            --vpc-connector $SERVERLESS_VPC_CONNECTOR \
            --set-env-vars DATABASE_URL=$DB_URL \
            --add-cloudsql-instances $CLOUD_RUN_PROJECT_ID:$CLOUD_RUN_REGION:$CLOUDSQL_INSTANCE_ID \
            --allow-unauthenticated \
            --quiet
