name: nextjs-cloud-run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    permissions:
      contents: write
      checks: write
      pull-requests: write
      id-token: write
    uses: cnguyen1901/reusable-workflow/.github/workflows/build-and-deploy.yml@main
    secrets: inherit
    with:
      environment: dev

